project:
  type: website

website:
  title: "bhanlam"
  description: "Lam Bhan's personal website"
  repo-url: https://github.com/bhanlam/bhanlam.github.io
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@bhanlam"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: publications/index.qmd
        text: "{{< fa file-lines >}} Publications"
      - href: cv/index.qmd
        text: "{{< fa address-card >}} Vitae"
    right:
      - icon: github
        href: https://github.com/bhanlam
      - icon: linkedin
        href: https://linkedin.com/in/lambhan
      - icon: twitter
        href: https://twitter.com/bhanlam
  page-footer:
    left: "{{< fa copyright >}} 2023, Lam Bhan"
    right:
      - icon: github
        href: https://github.com/bhanlam
      - icon: linkedin
        href: https://linkedin.com/in/lambhan
      - icon: twitter
        href: https://twitter.com/bhanlam

format:
  html:
    theme:
      light: zephyr
      dark: darkly
    max-width: 1920px
    css: styles.css
    toc: false

editor: visual

execute:
  freeze: auto

filters:
  - lightbox